### ISSUE TITLE
Problem inference

### ISSUE THREAD

**Issue by playdasegunda** [maxrmorrison/clpcnet#2]
Hello, your tool seems to be very interesting and will be very useful for changing the tempo in acapellas to have a better quality of the instrumentals using MDX-Net,

As I use Windows it would not be possible to use clpcnet as it seems it is only supported on Linux,

So I tried to create a Google Colab for your tool, but unfortunately I'm getting some errors,

Could you take a quick look and see what would be causing this problem:

https://colab.research.google.com/drive/19IDqORf4JBDKEezi52T40WcfZYCDphl1?usp=sharing

Please feel free if you need any editing,

Thanks in advance and I look forward to using this state-of-the-art tool,

Regards,
Lucas Rodrigues.

**Comment by maxrmorrison** [comment]
Hi Lucas. It looks like your HTK installation is not correct right now. A number of installation instructions have been modified, and the wrong version of HTK is being installed. You need to use HTK 3.4.0.

**Comment by playdasegunda** [comment]
Hi,

So I made some changes to the code and simplified it,

But I ended up finding numerous errors to install HTK 3.4

It's even saved the logs of the errors found, if you can take a look and see what could be causing these errors I'd be grateful,


https://colab.research.google.com/drive/19IDqORf4JBDKEezi52T40WcfZYCDphl1?usp=sharing


I changed makefile **line 77** as it contained space instead of 'TAB'

But even so, errors continued,

I assume you also had some problems with the HTK is very old and poorly configured,

Then you would be the best person to answer my doubts and almost everyone else who wants to install your tool,

Once again, thank you very much.

Regards,
Lucas Rodrigues.

**Comment by maxrmorrison** [comment]
Hi Lucas. A couple of things. One, I'm not sure HTK 3.4 == HTK 3.4.0. Often times, if you omit the last index it will use the latest version. Next, your errors indicate you're using OS X (`error: ‘darwin’ undeclared`). So you should use the modifications indicated [here](https://github.com/ucbvislab/p2fa-vislab#install-htk-34-note-341-will-not-work-get-htk-here).

**Comment by maxrmorrison** [comment]
I should add that CLPCNet doesn't really have the pitch accuracy for musical applications yet. Musical applications require greater pitch accuracy than speech. You might consider using [psola](https://github.com/maxrmorrison/psola).

**Comment by playdasegunda** [comment]
Thank you for the informations,

By the way, do you know any tools that change the tempo of a song without compromising the quality (the details)?

Because I've tested several and almost all compromise the quality,

Just one that I tested on https://dango.ai/

can change the tempo without causing distortion,

Thank you.

**Comment by maxrmorrison** [comment]
Elastique is an industry standard. That's been used by, e.g., Ableton. But yes, they all compromise the quality. There's no great solution for that problem yet.
