### ISSUE TITLE
No output file is generated

### ISSUE THREAD

**Issue by hagenw** [maxrmorrison/clpcnet#4]
I followed the installation instructions under https://github.com/maxrmorrison/clpcnet#without-docker and afterwards executed:

```bash
$ python -m clpcnet --constant_shift 2 --audio_files speech.wav --output_files speech_2.wav
```

but there is no output file generated nor an error message shown.

Does `--constant_shift` requires HTK to be installed first?

**Comment by maxrmorrison** [comment]
Pitch shifting does not require HTK. For some reason the context manager wasn't terminating some multiprocessing resources correctly. Fixed.

Although note that a 2x pitch-shift (especially upwards) usually won't sound great with CLPCNet.

**Comment by hagenw** [comment]
Thanks, it works now indeed.
I also adapted `2` to `1.122462048309373` as I wanted an increase of 2 semitones.
