### ISSUE TITLE
clpcnet cannot be properly installed

### ISSUE THREAD

**Issue by light1726** [maxrmorrison/clpcnet#5]
Hi! Nice project! Just encountered the following issue.
My conda version is 4.13.0, after doing "pip install -e .", the "import clpcnet" command exit the process directly and nothing happens.
Do you have any idea why this is the case?

**Comment by maxrmorrison** [comment]
Thanks for reporting this! The issue was that more recent versions of `protobuf` don't like some of my import masking (e.g., `from .model import model`). Fixed in the main branch by pinning `protobuf==3.20.1`.
