### ISSUE TITLE
Cannot generate output file

### ISSUE THREAD

**Issue by anupama-deo** [maxrmorrison/clpcnet#7]
Facing issue in understanding the arguments source_alignment_file, target_alignment_file, source_pitch_file, target_pitch_file etc When I give all the arguments from the list no output file is generated. Is target_alignment_file an. output file or the desired target time stretch file.

**Comment by maxrmorrison** [comment]
`output_file` is a file path and `target_alignment_file` contains a `pypar.Alignment` object (see docs [here](https://pypi.org/project/pypar/)) that has the desired alignment. It is not clear to me what function you are calling, or if you are using the command-line, so I don't know whether or not that behavior is intended.

**Comment by anupama-deo** [comment]
Hi Thanks so much for the reply. I wanted to use cmd (python -m clpcnet --audio_files.[] --output_files.......) but with all other arguments like source_alignment_file, target_alignment_files --source_pitch_files etc that is given in https://github.com/maxrmorrison/clpcnet#clpcnet , Can u give an example where other arguments are also used (other than just --constant_stretch and constant_shift) . What are the formats of other argument files? Also what are the upper and lower bounds for --constant_stretch and constant_shift that can generate decent audio

**Comment by maxrmorrison** [comment]
The pitch is a `numpy` file--one value every 10 ms. The alignment files are described in the `pypar` docs I linked above. As for the bounds, it depends on your input data. I usually keep it within 1/2 to 2.

**Comment by anupama-deo** [comment]
How to generate periodicity files, what is its format?

**Comment by anupama-deo** [comment]
what methods can be used to generate the pitch files?

**Comment by maxrmorrison** [comment]
https://github.com/maxrmorrison/clpcnet/blob/main/clpcnet/pitch.py
